Repository whittlem/pycryptobot, pull requests merged in 2021-07, with the labels that each got.

#361 Add "api_key_file" to the config to (eventually) replace "api_key / config"
  CHANGELOG.md
  README.md
  models/config/binance_parser.py
  models/config/coinbase_pro_parser.py
Labels: enhancement

#363 Accommodate for bigger ID in telegram.py, fix re.match bug with leading sign(s)
  models/chat/telegram.py
Labels: bug

#367 fix(getOrders): Retrieve only filled orders
  models/exchange/binance/api.py
Labels: bug, resolved

#368 changes logger to use one file everyday
  models/helper/LogHelper.py
  requirements.txt
Labels: enhancement

#370 Update README.md
  README.md
Labels: documentation

#384 Fix granularity problem in getHistoricalDateRange()
  README.md
  models/PyCryptoBot.py
Labels: bug, resolved

#389 Return local time if binance server time is not available
  CHANGELOG.md
  README.md
  models/exchange/binance/api.py
Labels: bug, resolved
